### ISSUE TITLE
X52 not detected

### ISSUE THREAD

**Issue by vekin** [jonasmalacofilho/liquidctl#212]
I haven't been able to get it to detect my Kraken X52

#lsusb|grep NZXT
Bus 003 Device 008: ID 1e71:2006 NZXT Smart Device V2
Bus 003 Device 006: ID 1e71:170e NZXT Kraken X
#.local/bin/liquidctl list
Device ID 0: Gigabyte RGB Fusion 2.0 8297 Controller (experimental)
Device ID 1: NZXT E850 (experimental)
Device ID 2: NZXT Smart Device V2

I can control the colors/pump/fans of the X52 with colctl.

**Comment by jonasmalacofilho** [comment]
`colctl` unbinds the `usbhid` driver from the device, and fails to rebind it once it's done.  Because of this, the device is not accessible to liquidctl after running `colctl`.  See [Device not listed (Linux)](https://github.com/jonasmalacofilho/liquidctl#device-not-listed-linux) for more information.
