### ISSUE TITLE
How to reset / set to default a fan curve?

### ISSUE THREAD

**Issue by MPasadu** [jonasmalacofilho/liquidctl#243]
I've set a fan curve and a pump curve for my Kraken X62.
Now I actually only need the pump curve set by liquid temp and want to run the fan curve via my motherboard's bios (cpu temp). 

But I can't find how to disable/reset the fan curve now so my motherboard curve is used instead.  
These settings seem to be stored on the hardware itself, right? But when I override them with NZXT's Cam, and then close CAM, the settings are reset to liquidctl's settings.

**Comment by jonasmalacofilho** [comment]
To restore the default settings, power off the cooler.  Depending on your power saving/ErP motherboard settings this will require turning off the PSU (and waiting for all caps to be drained); because the cooler's controller, as other USB devices, can be powered from the 5 V Stand-by rail.

---

That said, you might not actually need that, since:

- the default/factory settings are also curves based on liquid temperature, just using 5°C increments
- there is no scenario where a conflict is possible between cooler and the motherboard: if the fans are connected to the cooler, the motherboard can't control them; if they are directly connected to the motherboard, the cooler can't control them
- on the other hand, CAM's curves based on CPU temperature run on the host's CPU, not run in BIOS (on motherboard firmware) or in the cooler; and when CAM closes the motherboard or cooler will always need to take over (depending on where the fans are connected to)

Hope this helps.
