### ISSUE TITLE
Kraken X61 pump makes grinding noises with liquidctl/libusbK

### ISSUE THREAD

**Issue by cwallaceio** [jonasmalacofilho/liquidctl#66]
What the hell, I followed instructions and did all the steps to utilize this program. After initializing everything went to 100% speed. Now after shutting down and rebooting my pump is making grinding noises. How do I fix this?

**Comment by cwallaceio** [comment]
You know what please just tell me how to 100% uninstall this software. I already removed the libusbk driver. Don't know what else to do. Whatever your software did it saved it to the pump itself.

**Comment by jonasmalacofilho** [comment]
Turn off the PSU for a few seconds.  That will reset the device, and liquidctl does not use commands to permanently store settings on the device.

---

From what you describe, having your pump and fans running at 100% isn't something you regularly did.  It's possible that something got displaced by that (e.g. air bubbles in the loop).

Software wise, you can go back to running whatever program you used before.  If you used the pre-built liquidctl.exe then there's nothing to uninstall on that end.  And you already mentioned you removed the custom driver...

Which brings me to my final questions: which instructions and which version of liquidctl were you using?  I [usually recommend the WinUSB driver](https://github.com/jonasmalacofilho/liquidctl/blob/master/README.md#additional-requirements-on-windows), not libusbk...

**Comment by cwallaceio** [comment]
Yes libusbk. Not WinUSB but the docs were saying to use that. I can try
with the .exe file.

**Comment by jonasmalacofilho** [comment]
Which docs?

**Comment by cwallaceio** [comment]
The readme says libusb is recommended.

**Comment by jonasmalacofilho** [comment]
Actually, it doesn't, [it recommends WinUSB](https://github.com/jonasmalacofilho/liquidctl/blob/master/README.md#additional-requirements-on-windows).  So which README then?

---

Honestly, this doesn't matter that much, since generally (and in this particular case) software cannot break hardware.  The firmware only exposes a very limited range of options, all of which within spec (e.g. running the pump at 100% is certainly within spec).

Which is why I mentioned that it's probably just some temporary displacement of air bubbles or something like that.

You can go back to using the software you used before.  Remove liquidctl and the custom driver.  Also reinstall the Asetek driver and/or CAM.

Alternatively I can guide you through how I would deal with this myself, both to clear any air bubbles or diagnose possible hardware problems.

**Comment by jonasmalacofilho** [comment]
By the way, the behavior you describe resembles what would happen if you failed to pass `--legacy-690lc` to **all** liquidctl commands when using it with an old Kraken.

Additionally, it's possible that you're running some random old code, from before the support for the X61 was stabilized, or even, because of the discrepancy on the driver recommendation, something from a third-party source.  In either of these cases the documentation could fail to stress the importance of passing `--legacy-690lc`, or even of initializing the device.

The steps I would take would be to:

 - uninstall the custom driver and remove liquidctl
 - reset the device by leaving the PSU off for a while
 - use the WinUSB driver
 - use liquidctl v1.2.0 or v1.3.0rc1
 - pass `--legacy-690lc` and, temporarily, `--debug`
 - initialize before any status or set commands

```
liquidctl list --legacy-690lc --debug
liquidctl initialize --legacy-690lc --debug
liquidctl status --legacy-690lc --debug

liquidctl set fan speed 70 --legacy-690lc --debug
liquidctl status --legacy-690lc --debug

liquidctl set pump speed 70 --legacy-690lc --debug
liquidctl status --legacy-690lc --debug
```

**Comment by cwallaceio** [comment]
Thanks for the help, this is the part of the README that I saw:

![Capture](https://user-images.githubusercontent.com/37254294/68260321-b6840600-000a-11ea-9acb-8f999a83cd32.PNG)

I was using v1.3.0rc1 and I tried appending `--legacy-609lc` to all commands. I've tried the WinUSB driver as well as the reset. What worked was removing these drivers and reinstalling CAM. That removed the grinding noise. Perhaps some x61's aren't good at using this software for whatever reason (bug or something).

**Comment by jonasmalacofilho** [comment]
I'm happy to hear that the noise is gone!

> Perhaps some x61's aren't good at using this software for whatever reason (bug or something).

Perhaps... what firmware version is your X61 is running?

I'm going to leave the issue open (at least for now) and I'd be happy to work with you to fix the problem.  Let me know if it's something you're interested in.

The first step would be to reinstall the WinUSB driver and liquidctl 1.3.0rc1 and post the output from the following commands (and only them):

```
liquidctl list --legacy-690lc --debug
liquidctl initialize --legacy-690lc --debug
# wait a few seconds

liquidctl status --legacy-690lc --debug
liquidctl set fan speed 70 --legacy-690lc --debug
# wait a few seconds

liquidctl status --legacy-690lc --debug
liquidctl set pump speed 70 --legacy-690lc --debug
# wait a few seconds

liquidctl status --legacy-690lc --debug
```

---

I see where the confusion comes from: I mention libusb (library, not driver), then recommend the WinUSB driver, then go back to discuss a particular quirk with recent libusb (not libusbK) versions.  And I guess libusb and libusbK are easy to mix up.

I'll improve this, specially because there's a chance that something specific to libusbK triggered the issue, which then persisted until the Asetek driver was reinstalled.

P.S. Your screenshot crops out _"with Zadig, selecting the WinUSB"_ from the first paragraph.

**Comment by jonasmalacofilho** [comment]
@cwallaceio 

Please let me know the firmware version even if you don't have the time to debug the issue right now.

**Comment by jonasmalacofilho** [comment]
@cdgriffith which kernel driver are you using on Windows?
